from enum import Enum

# Define an enumeration class
class Screens(Enum):
    SPLASH = "SPLASH"
    MAIN = "MAIN"
    SELECT_LANGUAGE = "SELECT_LANGUAGE"
    SELECT_CHARACTER = "SELECT_CHARACTER"
    SELECT_PET = "SELECT_PET"
    REGIONS = "REGIONS"
    TRAINING_REGIONS = "TRAINING_REGIONS"
    WATER_REGION = "WATER_REGION"
    WATER_TRAINING_REGION = "WATER_TRAINING_REGION"
    WATER_REGION_LILY = "WATER_REGION_LILY"
